### ISSUE TITLE
疑问。

### ISSUE THREAD

**Issue by Huer-H** [CaA23187/TasNet#1]
您好，
 我发现您的代码好像跟matlab合成数据的方法不太一致，
您是直接将s1和s2直接相+，得到的mix，原始论文中提到的是在[-5,5]的信噪比中进行mix操作。
可以提供复现的结果吗？

**Comment by CaA23187** [comment]
感谢提醒，当时阅读论文没注意这个，我是在prepareData.py文件中的write_spectra_to_HDF5函数中第150行进行数据合成的，若想改变信噪比可以自己设置倍数进行合成。
由于我GPU比较差，训练起来较慢，目前迭代50个epoch后效果较差，我也正在寻找解决方案。

**Comment by Huer-H** [comment]
嗯嗯，多谢！
